---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: kyverno.github.io
  namespace: ${workspaceNamespace}
spec:
  url: https://kyverno.github.io/kyverno
  interval: 10m
  timeout: 1m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: kyverno
      sourceRef:
        kind: HelmRepository
        name: kyverno.github.io
        namespace: ${workspaceNamespace}
      version: 3.0.1
  install:
    remediation:
      retries: 30
  interval: 15s
  releaseName: kyverno
  targetNamespace: ${releaseNamespace}
  upgrade:
    remediation:
      retries: 30
  valuesFrom:
    - kind: ConfigMap
      name: kyverno-3.0.1-d2iq-defaults
