---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: falcosecurity.github.io
  namespace: ${workspaceNamespace}
spec:
  url: https://falcosecurity.github.io/charts
  interval: 10m
  timeout: 1m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: falco
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: falco
      sourceRef:
        kind: HelmRepository
        name: falcosecurity.github.io
        namespace: ${workspaceNamespace}
      version: 2.4.3
  install:
    remediation:
      retries: 30
  interval: 15s
  releaseName: falco
  targetNamespace: ${releaseNamespace}
  upgrade:
    remediation:
      retries: 30
  valuesFrom:
    - kind: ConfigMap
      name: falco-2.4.3-d2iq-defaults