---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: confluent-operator
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: confluent-for-kubernetes
      sourceRef:
        kind: HelmRepository
        name: confluentinc
        namespace: ${workspaceNamespace}
      version: 0.771.13
  install:
    remediation:
      retries: 30
  interval: 15s
  releaseName: confluent-operator
  targetNamespace: ${releaseNamespace}
  upgrade:
    remediation:
      retries: 30
  valuesFrom:
    - kind: ConfigMap
      name: cfk-0.771.13-d2iq-defaults