---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: gitlab
  namespace: ${workspaceNamespace}
spec:
  url: https://charts.gitlab.io/
  interval: 10m
  timeout: 1m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: gitlab
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: ${workspaceNamespace}
      version: 7.4.1
  install:
    remediation:
      retries: 30
  interval: 15s
  releaseName: gitlab
  targetNamespace: ${releaseNamespace}
  upgrade:
    remediation:
      retries: 30
  valuesFrom:
    - kind: ConfigMap
      name: gitlab-7.4.1-mdr-defaults