---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: gitea-charts
  namespace: ${workspaceNamespace}
spec:
  url: https://dl.gitea.io/charts/
  interval: 10m
  timeout: 1m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: gitea
      sourceRef:
        kind: HelmRepository
        name: gitea-charts
        namespace: ${workspaceNamespace}
      version: 9.1.0
  install:
    remediation:
      retries: 30
  interval: 15s
  releaseName: gitea
  targetNamespace: ${releaseNamespace}
  upgrade:
    remediation:
      retries: 30
  valuesFrom:
    - kind: ConfigMap
      name: gitea-9.1.0-mdr-defaults