---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-12.6.5-mdr-defaults
  namespace: ${releaseNamespace}
data:
  values.yaml: |
    ---
    auth:
      database: petclinic
      username: petclinic
      password: petclinic
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        labels:
          prometheus.kommander.d2iq.io/select: "true"