---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-12.6.5-mdr-defaults
  namespace: ${releaseNamespace}
data:
  values.yaml: |
    ---
    auth:
      database: demoapp
      username: demoapp
      password: demoapp
    # metrics:
    #   enabled: true
    #   serviceMonitor:
    #     enabled: true
    #     labels:
    #       prometheus.kommander.d2iq.io/select: "true"
    primary:
      extendedConfiguration: |
        password_encryption = md5
        shared_preload_libraries = 'pg_stat_statements'


