---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-12.6.5-mdr-defaults
  namespace: ${releaseNamespace}
data:
  values.yaml: |
    ---
    global:
      postgresql:
        auth:
          database: petclinic
          username: petclinic
          password: petclinic
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true