---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-12.6.5-mdr-defaults
  namespace: ${releaseNamespace}
data:
  values.yaml: |
    ---
    metrics:
      serviceMonitor:
        enabled: true