---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-1.15.4-mdr-defaults
  namespace: ${releaseNamespace}
data:
  values.yaml: |
    ---
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.tls: "true"
      ingressClassName: kommander-traefik
      hosts:
      - host: pgadmin.workload.dkp.lab.mark.eek
        paths:
        - path: /
          pathType: Prefix

    env:
      email: admin@example.com

    serverDefinitions:
      enabled: true
      servers:
        project:
          Name: "Project Deployed Server"
          Group: "Servers"
          Port: 5432
          Username: "postgres"
          Host: "postgresql"
          SSLMode: "prefer"
          MaintenanceDB: "postgres"


