---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: confluentinc
  namespace: ${workspaceNamespace}
spec:
  url: https://packages.confluent.io/helm
  interval: 10m
  timeout: 1m