---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: secrets-store-csi-driver
  namespace: ${workspaceNamespace}
spec:
  url: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
  interval: 10m
  timeout: 1m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: secrets-store-csi-driver
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: secrets-store-csi-driver
      sourceRef:
        kind: HelmRepository
        name: secrets-store-csi-driver
        namespace: ${workspaceNamespace}
      version: 1.3.4
  install:
    remediation:
      retries: 30
  interval: 15s
  releaseName: csi
  targetNamespace: ${releaseNamespace}
  upgrade:
    remediation:
      retries: 30
  valuesFrom:
    - kind: ConfigMap
      name: secrets-store-1.3.4-mdr-defaults