---
apiVersion: v1
kind: ConfigMap
metadata:
  name: secrets-store-1.3.4-mdr-defaults
  namespace: kube-system
data:
  values.yaml: |
    ---
    syncSecret:
      enabled: true
    enableSecretRotation: true