---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: ${releaseNamespace}
  labels:
    kommander.d2iq.io/dkp-airgapped: unsupported
spec:
  url: "${helmMirrorURL:=https://prometheus-community.github.io/helm-charts}"
  interval: 10m
  timeout: 1m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql-exporter
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: prometheus-postgres-exporter
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: ${releaseNamespace}
      version: 4.8.0
  install:
    remediation:
      retries: 30
  interval: 15s
  releaseName: postgresql-exporter
  targetNamespace: ${releaseNamespace}
  upgrade:
    remediation:
      retries: 30
  valuesFrom:
    - kind: ConfigMap
      name: postgresql-exporter-4.8.0-mdr-defaults